### ISSUE TITLE
Billpay/Billsafe detailed payment information

### ISSUE THREAD

**Issue by dermatz** [firegento/firegento-pdf#94] opened 2013-12-04 09:15 UTC
When we activate the PDF Engine "Standard Germany" the detailed billing information of external Billing Services are not displayed.

We use Billsafe for Invoice transactions.
Billsafe normaly add transaction informations (subject,account number, Payment Information ..) into the PDF Invoice. 

But in Firegento PDF Engine only the title is displayed.

See it here:
http://goo.gl/wVjdWE

**Comment by kkoepke** [comment] 2015-01-14 13:25
Habt ihr inzwischen eine Lösung? Ich stehe auch noch immer vor dem selben Problem.

**Comment by dermatz** [comment] 2015-01-14 13:35
@kkoepke - Mit der aktuellen Firegento PDF Version und der Aktuellen Billsafe-Version ist nun alles korrekt. Die Rechnungs-PDF sollte eigentlich alle Informationen von Billsafe enthalten.

**Comment by kkoepke** [comment] 2015-01-14 13:37
@dermatz Ok, ich werde es testen. Im betreffenden Shop ist es in dem Fall Billpay statt Billsafe.

**Comment by Schrank** [comment] 2015-01-14 19:35
Please use english here, so everyone understands the problem.

The problem is, that often these payment provider rewrite the pdf models, payment or invoice models to achieve this. We can't do anything about this. The provider have to do it the magento way (don't know how this works atm) to make this possible, when the pdf engine changes.

**Comment by unifiedarts** [comment] 2015-11-27 12:34
hi, we have here the same problem with Billpay, the payment information is not displayed in the firegento pdf. We tested with the magento standard pdf engine and there are all related informations about the payment, see here:

![magento-billpay-firegento-pdf](https://cloud.githubusercontent.com/assets/7428697/11441322/559705f4-950b-11e5-8d5e-6a4cfa985a86.jpg)

magento 1.9.1
latest firegento pdf module
latest billpay module version

So in fact it seems to be an firegento-pdf issue, it would be nice to get some help to implement the payment details into the invoice and an future fix/update of your module

**Comment by Schrank** [comment] 2015-11-27 12:57
Reopen to check what magento core is doing, so maybe we can just copy this.

**Comment by Schrank** [comment] 2015-11-27 12:57
Are you using current develop branch?

**Comment by Schrank** [comment] 2015-11-27 13:07
Sorry, please read https://github.com/firegento/firegento-pdf/issues/94#issuecomment-29820505 if they are rewriting pdf parts, of course it works in core but not for us.

**Comment by unifiedarts** [comment] 2015-11-27 13:13
nope, not the develop branch. who? billpay module?

**Comment by unifiedarts** [comment] 2015-12-02 14:06
hello,

we updated the module now from the develop branch. it seems that there is still that problem. so if there is no opportunity to add the payment informations for Billpay or other ones, then the module is incomplete for real live shops. Pls feedback if there are any thoughts to update that

**Comment by Schrank** [comment] 2015-12-02 14:19
I checked the BillPay module and they are using \Billpay_Model_Rec::$_infoBlockType, so this should theoretically be used. We need to check why this is not the case.

So I want to check what is going on and then decide whether this is a bug or not. I have no idea when to do it, so if you want to have it shortly, write @sprankhub or me an email, so we can give you an offer to implement this "now".

**Comment by sprankhub** [comment] 2015-12-07 14:01
I checked the current version of the Billpay extension (1.7.3) and saw that they already implemented an observer method, which inserts their block into our notes section. Awesome! Unfortunately, it is not defined in their config.xml, so that it currently does not work. I just wrote them a mail and asked for the reasons. Let us see what they answer. In any case, you can fix it yourself by adding this to the config.xml:

    <global>
        <events>
            <firegento_pdf_invoice_insert_note>
                <observers>
                    <namespace_module>
                        <class>billpay/observer</class>
                        <method>handleFireGentoPdfNotes</method>
                    </namespace_module>
                </observers>
            </firegento_pdf_invoice_insert_note>
        </events>
    </global>

If they include that into their extension, all is good and we can close this issue. I do not see any reason why they should not do that.

**Comment by unifiedarts** [comment] 2015-12-08 13:03
@sprankhub thanks for the hint. we updated both modules: Billpay 1.7.3 & firegento pdf 1.3.0. Unfortunately its not working either. We added the event mentioned to the config of billpay module, but i have seen that in the firegento pdf is also the same event. so where do we have to add that stuff? thx

**Comment by sprankhub** [comment] 2015-12-08 13:13
If you add my snippet to the right config.xml of the Billpay extension, it works. You could post the full config.xml here, so that we can shortly check it.

**Comment by unifiedarts** [comment] 2015-12-08 14:13
billsafe config.xml events part, should be right:

        <events>
            <checkout_type_onepage_save_order>
                <observers>
                    <billpay_save_order>
                        <type>singleton</type>
                        <class>billpay/observer</class>
                        <method>beforeSaveOrder</method>
                        <args></args>
                    </billpay_save_order>
                </observers>
            </checkout_type_onepage_save_order>

            <checkout_type_onepage_save_order_after>
                <observers>
                    <billpay_save_order>
                        <type>singleton</type>
                        <class>billpay/observer</class>
                        <method>afterSaveOrder</method>
                        <args></args>
                    </billpay_save_order>
                </observers>
            </checkout_type_onepage_save_order_after>

            <controller_action_postdispatch_checkout_onepage_saveOrder>
                <observers>
                    <billpay_save_order>
                        <type>singleton</type>
                        <class>billpay/observer</class>
                        <method>saveOrderPostDispatch</method>
                        <args></args>
                    </billpay_save_order>
                </observers>
            </controller_action_postdispatch_checkout_onepage_saveOrder>

            <sales_convert_quote_payment_to_order_payment>
                <observers>
                    <convert_quote_event_handler>
                        <type>model</type>
                        <class>billpay/observer</class>
                        <method>convertQuoteToOrder</method>
                        <args></args>
                    </convert_quote_event_handler>
                </observers>
            </sales_convert_quote_payment_to_order_payment>

            <sales_quote_collect_totals_before>
                <observers>
                    <billpay_set_defaults>
                        <type>model</type>
                        <class>billpay/observer</class>
                        <method>setDefaults</method>
                    </billpay_set_defaults>
                </observers>
            </sales_quote_collect_totals_before>

            <firegento_pdf_invoice_insert_note>
                <observers>
                    <namespace_module>
                        <class>billpay/observer</class>
                        <method>handleFireGentoPdfNotes</method>
                    </namespace_module>
                </observers>
            </firegento_pdf_invoice_insert_note>

        </events>


===== firegento events part:

        <events>
            
                
                    
                        
                        
                    
                
            
            <firegento_pdf_shipment_insert_note>
                <observers>
                    <firegento_pdf>
                        <class>firegento_pdf/observer</class>
                        <method>addShipmentNotes</method>
                    </firegento_pdf>
                </observers>
            </firegento_pdf_shipment_insert_note>
            <firegento_pdf_creditmemo_insert_note>
                <observers>
                    <firegento_pdf>
                        <class>firegento_pdf/observer</class>
                        <method>addCreditmemoNotes</method>
                    </firegento_pdf>
                </observers>
            </firegento_pdf_creditmemo_insert_note>
            <firegento_pdf_invoice_edit_page>
                <observers>
                    <firegento_pdf>
                        <class>firegento_pdf/observer</class>
                        <method>addInvoiceBarcode</method>
                    </firegento_pdf>
                </observers>
            </firegento_pdf_invoice_edit_page>
            <firegento_pdf_shipment_edit_page>
                <observers>
                    <firegento_pdf>
                        <class>firegento_pdf/observer</class>
                        <method>addShipmentBarcode</method>
                    </firegento_pdf>
                </observers>
            </firegento_pdf_shipment_edit_page>
        </events>

**Comment by Schrank** [comment] 2015-12-08 14:17
looks good, flushed cache=

**Comment by sprankhub** [comment] 2015-12-08 14:21
The problem may be that you only added the observer under the `frontend` tag. It should (also) be under the `adminhtml` tag or simply under the `global` tag.

**Comment by unifiedarts** [comment] 2015-12-08 14:22
sure, cache cleaned, cache flushed, no caching engines active

**Comment by unifiedarts** [comment] 2015-12-08 14:24
@sprankhub - yes this could be the right solution - thx i will try that

**Comment by unifiedarts** [comment] 2015-12-08 14:55
great, its working, adding it to the global tag resolves the problem. many thanks dude!

**Comment by sprankhub** [comment] 2016-01-11 13:06
Current status is that Billpay wants to test my patch "against all corner cases" some time this year.

**Comment by sprankhub** [comment] 2016-03-05 13:04
No idea when Billpay will finally update their extension and include the full XML. I now implemented an extension, which adds the detailed Billpay payment information on FireGento PDF invoices: https://github.com/firegento/firegento-pdf-billpay

**Closed by sprankhub** 2016-03-05 13:04 UTC
Labels: wontfix
